### PR TITLE
Allow users to specify a build target directory - useful if for examp…

### PR DESCRIPTION
**Pull request by opalfroot**
This small changes allows users to specify a build target path. I find this useful in cases where my project has many modules and I'd like to be able to specify the path of say a REST service to be rebuild and run.

### CODE REVIEW

**Comment by markbates** [comment]
How is this different from the `BuildPath`?

**Comment by opalfroot** [comment]
The BuildPath is where the binary goes and the BuildTargetPath is where the source resides - ie look here for buildable code. 

The idea behind this is you can specify a specific package to rebuild on change and you dont need to rely on having a main somewhere at the top level.  This is a likely scenario for people building cli's and web services in the same codebase using shared middle code.

**Comment by markbates** [comment]
In that case, couldn't we use the `AppRoot` config setting instead of adding a new one?

**Comment by opalfroot** [comment]
That wouldn't really work. That setting is used by the walker which needs to know about all the code you have in your project - not just the build target directory.

**Comment by markbates** [comment]
Merged! Thanks!

**Comment by opalfroot** [comment]
Thank you!


________________________________

**Pull request merged**
