### PR TITLE
Watcher Filenotify interface (Polling & fsnotify)

### LINKED ISSUE #31: Allow for the Watcher to poll the file system
Unfortunately, inotify is not implemented sufficiently in the docker ecosystem to be the only available option for refresh:

__Problem Statement:__ Docker for Windows running inside of Hyper-V mounts shared volumes using Samba/CIFS. Unfortunately, the CIFS implementation in the linux kernel doesn't support inotify events.

There are more examples that aren't just Windows specific (including some legacy Docker for Mac issues that have since been patched) that I won't list here, but it's important to highlight that inotify is great when available, but cannot be relied upon.

> There is an [outstanding issue on the `fsnotify` project](https://github.com/fsnotify/fsnotify/issues/9) since 2014 about addressing this through their package, but I doubt there will be any meaningful traction on the issue, so we should patch it here first imo.

Examples of others solving this similarly:

* [smartystreets/goconvey](https://github.com/smartystreets/goconvey/tree/master/web/server/watch) uses polling exclusively, allowing them to sidestep the "too many files" error, and work agnostic of inotify/fsnotify.
* [docker](https://github.com/moby/moby/blob/master/pkg/filenotify/filenotify.go) describes a `FileWatcher` interface that allows them to leverage `fsnotify` or their `poller`

Implementation examples:

* https://github.com/moby/moby/blob/master/pkg/filenotify
* https://github.com/radovskyb/watcher

It seems since moby/moby has exposed `filenotify` as a `pkg`, it's probably in best interest to leverage that package. Either vendoring this, or bringing it in as a third party seems like the best of both worlds.

### PR DESCRIPTION
**Pull request by syntaqx**
* Pulls in [github.com/docker/docker/pkg/filenotify](https://github.com/moby/moby/tree/master/pkg/filenotify) as a managed dep (Apache License, Version 2.0)
  * There's a conflict with `[Ss]irupsen/logrus` naming in the dependency chain
  * Docker committed their `vendor` folder for the CLI, so importing the real package prior to Go 1.11 isn't worth the effort.
* Removes `pkg` from `.gitignore` for the `filenotify` package. This is a common pattern, we should keep it.
* Adds a `force_polling` optional configuration to enable the poller.
* Accepts the interface where needed rather than `fsnotify`'s struct

Closes #31 

While this does introduce a new dependency, this can be included as a minor version release as it does not introduce any backwards incompatible functionality.

### CODE REVIEW

**Comment by syntaqx** [comment]
~~Hold on merging this as so I can review it a bit more indepth tomorrow, I'm having some flaky reliability with the binary right now.. It could be my system, but I want to test a few more things.~~

This was my bad, I broke my `.refresh.yml` file with a new format I was playing with and forgot to reset it. This is good to go!

**Comment by syntaqx** [comment]
@markbates Let me know if you need anything else from me on this, but we're good to merge as far as I'm concerned.

**Comment by markbates** [comment]
I haven’t had the time to even look at this, sorry. I will try over the next few days.

-----------
Mark Bates

**Review by markbates — CHANGES_REQUESTED** [review]
Please remove the sub package `pkg`.

**Comment by syntaqx** [comment]
Is the `pkg` convention not something you want to utilize? Personally I'm a big fan of the formality, but if you're not I suppose I can pull it back out.

**Comment by markbates** [comment]
Please remove it. Thanks.

-----------
Mark Bates

**Review by markbates — APPROVED** [review]

**Comment by markbates** [comment]
Looks good. I want to run this on some more platforms before I merge.

**Pull request merged**
